SCREENSIZE = (1024, 768)
SCREENSIZE_CENTER = (SCREENSIZE[0] / 2, SCREENSIZE[1] / 2)

WALL_PATH = 'assets\\wall.png'
GRASS_PATH = 'assets\\grass.png'
MAP_PATH = 'assets\\map.json'

TILEWIDTH = 64
TILEHEIGHT = 64
TILEHEIGHT_HALF = TILEHEIGHT / 2
TILEWIDTH_HALF = TILEWIDTH / 2

MISSING = object()